/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	hleasev1alpha1 "harmonycloud.cn/agents/node-agent/pkg/apis/hlease/v1alpha1"
	versioned "harmonycloud.cn/agents/node-agent/pkg/client/clientset/versioned"
	internalinterfaces "harmonycloud.cn/agents/node-agent/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "harmonycloud.cn/agents/node-agent/pkg/client/listers/hlease/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HLeaseInformer provides access to a shared informer and lister for
// HLeases.
type HLeaseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HLeaseLister
}

type hLeaseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHLeaseInformer constructs a new informer for HLease type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHLeaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHLeaseInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHLeaseInformer constructs a new informer for HLease type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHLeaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IsolateV1alpha1().HLeases(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IsolateV1alpha1().HLeases(namespace).Watch(context.TODO(), options)
			},
		},
		&hleasev1alpha1.HLease{},
		resyncPeriod,
		indexers,
	)
}

func (f *hLeaseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHLeaseInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hLeaseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&hleasev1alpha1.HLease{}, f.defaultInformer)
}

func (f *hLeaseInformer) Lister() v1alpha1.HLeaseLister {
	return v1alpha1.NewHLeaseLister(f.Informer().GetIndexer())
}
