/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "harmonycloud.cn/agents/node-agent/pkg/apis/hlease/v1alpha1"
	scheme "harmonycloud.cn/agents/node-agent/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HLeasesGetter has a method to return a HLeaseInterface.
// A group's client should implement this interface.
type HLeasesGetter interface {
	HLeases(namespace string) HLeaseInterface
}

// HLeaseInterface has methods to work with HLease resources.
type HLeaseInterface interface {
	Create(ctx context.Context, hLease *v1alpha1.HLease, opts v1.CreateOptions) (*v1alpha1.HLease, error)
	Update(ctx context.Context, hLease *v1alpha1.HLease, opts v1.UpdateOptions) (*v1alpha1.HLease, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HLease, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HLeaseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HLease, err error)
	HLeaseExpansion
}

// hLeases implements HLeaseInterface
type hLeases struct {
	client rest.Interface
	ns     string
}

// newHLeases returns a HLeases
func newHLeases(c *IsolateV1alpha1Client, namespace string) *hLeases {
	return &hLeases{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hLease, and returns the corresponding hLease object, and an error if there is any.
func (c *hLeases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HLease, err error) {
	result = &v1alpha1.HLease{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hleases").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HLeases that match those selectors.
func (c *hLeases) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HLeaseList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HLeaseList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hLeases.
func (c *hLeases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a hLease and creates it.  Returns the server's representation of the hLease, and an error, if there is any.
func (c *hLeases) Create(ctx context.Context, hLease *v1alpha1.HLease, opts v1.CreateOptions) (result *v1alpha1.HLease, err error) {
	result = &v1alpha1.HLease{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hLease).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a hLease and updates it. Returns the server's representation of the hLease, and an error, if there is any.
func (c *hLeases) Update(ctx context.Context, hLease *v1alpha1.HLease, opts v1.UpdateOptions) (result *v1alpha1.HLease, err error) {
	result = &v1alpha1.HLease{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hleases").
		Name(hLease.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hLease).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the hLease and deletes it. Returns an error if one occurs.
func (c *hLeases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hleases").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hLeases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hleases").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched hLease.
func (c *hLeases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HLease, err error) {
	result = &v1alpha1.HLease{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hleases").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
